"""A small simulated store with the same shape and the same kinds of mess as
the real workbook.

Customers are generated by the processes the value models assume (BG/NBD for
when people buy and when they quietly stop, Gamma-Gamma for how much they
spend), so later layers can be checked against parameters we know. Then known
amounts of dirt are planted on top: duplicate lines, an overlap between the
two sheets, guest orders, postage, free lines, stock corrections, bad debt
entries, full cancellations and partial returns. The tests check that the
cleaning removes exactly what was planted and nothing else.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

START = pd.Timestamp("2009-12-01 08:00")
END = pd.Timestamp("2011-12-09 17:00")
SHEET2_START = pd.Timestamp("2010-12-01")
SHEET1_END = pd.Timestamp("2010-12-10")  # sheet 1 runs a few days into sheet 2, like the real file

# true BG/NBD and Gamma-Gamma parameters, time in weeks, money in GBP
TRUE = {"r": 0.75, "alpha": 6.0, "a": 0.9, "b": 3.5, "p": 4.0, "q": 3.5, "gamma": 250.0}
COUNTRIES = ["United Kingdom"] * 9 + ["Germany", "France", "EIRE", "Netherlands"]


def _catalog(rng, n=300):
    codes = [f"{20000 + i}" + ("" if rng.random() < 0.8 else "ABC"[rng.integers(3)]) for i in range(n)]
    prices = np.round(rng.choice([0.42, 0.85, 1.25, 1.65, 2.1, 2.95, 3.75, 4.95, 7.95, 12.75], n), 2)
    return pd.DataFrame({"stock_code": codes, "description": [f"ITEM {c}" for c in codes], "price": prices})


def _time_on(day: pd.Timestamp, rng) -> pd.Timestamp:
    return day.normalize() + pd.Timedelta(minutes=int(rng.integers(8 * 60, 18 * 60)))


def simulate_customers(rng, n: int) -> pd.DataFrame:
    span_weeks = (END - START).days / 7
    # more customers arrive early, as in a store that is already established
    first = START + pd.to_timedelta(rng.beta(1.0, 1.6, n) * span_weeks * 7, unit="D")
    lam = rng.gamma(TRUE["r"], 1 / TRUE["alpha"], n)
    p_drop = rng.beta(TRUE["a"], TRUE["b"], n)
    nu = rng.gamma(TRUE["q"], 1 / TRUE["gamma"], n)
    return pd.DataFrame({
        "customer_id": [str(12346 + i) for i in range(n)],
        "first": first, "lam": lam, "p_drop": p_drop, "nu": nu,
        "country": rng.choice(COUNTRIES, n),
    })


def simulate_orders(rng, customers: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for c in customers.itertuples():
        t = c.first
        alive_until = None
        while t <= END:
            spend = rng.gamma(TRUE["p"], 1 / c.nu)
            rows.append((c.customer_id, c.country, _time_on(t, rng), spend))
            if rng.random() < c.p_drop:
                alive_until = t
                break
            gap = rng.exponential(1 / c.lam)
            if gap > 200:  # past the end of the data anyway
                break
            t = t + pd.Timedelta(weeks=gap)
        customers.loc[c.Index, "dropped_at"] = alive_until
    return pd.DataFrame(rows, columns=["customer_id", "country", "invoice_date", "spend"])


def _lines_for(rng, codes, descs, prices, spend):
    k = int(np.clip(rng.poisson(6) + 1, 1, 25))
    idx = rng.choice(len(codes), k, replace=False)
    qty = np.maximum(1, np.round(spend / (k * prices[idx]))).astype(int)
    return codes[idx], descs[idx], prices[idx], qty


def build(seed: int = 11, n_customers: int = 2500, n_guest_orders: int = 600) -> tuple[pd.DataFrame, dict]:
    rng = np.random.default_rng(seed)
    catalog = _catalog(rng)
    customers = simulate_customers(rng, n_customers)
    orders = simulate_orders(rng, customers)

    guests = pd.DataFrame({
        "customer_id": None, "country": "United Kingdom",
        "invoice_date": [_time_on(START + pd.Timedelta(days=float(d)), rng)
                         for d in rng.uniform(0, (END - START).days, n_guest_orders)],
        "spend": rng.gamma(2.0, 150.0, n_guest_orders),
    })
    orders = pd.concat([orders, guests], ignore_index=True).sort_values("invoice_date", kind="stable")
    orders["invoice"] = [str(489434 + i) for i in range(len(orders))]

    codes, descs, prices = (catalog[c].to_numpy() for c in ("stock_code", "description", "price"))
    cols = {k: [] for k in ("invoice", "stock_code", "description", "quantity", "invoice_date",
                            "price", "customer_id", "country")}
    for o in orders.itertuples():
        c, d, p, q = _lines_for(rng, codes, descs, prices, o.spend)
        n = len(c)
        cols["stock_code"].extend(c); cols["description"].extend(d)
        cols["price"].extend(p); cols["quantity"].extend(q)
        for key, val in (("invoice", o.invoice), ("invoice_date", o.invoice_date),
                         ("customer_id", o.customer_id), ("country", o.country)):
            cols[key].extend([val] * n)
    clean_lines = pd.DataFrame(cols)
    clean_lines = clean_lines[["invoice", "stock_code", "description", "quantity", "invoice_date",
                               "price", "customer_id", "country"]]

    truth = {"customers": customers, "true_params": TRUE,
             "guest_lines": int(clean_lines["customer_id"].isna().sum())}
    known = clean_lines[clean_lines["customer_id"].notna()]
    next_inv = [900000]

    def new_invoice(prefix=""):
        next_inv[0] += 1
        return f"{prefix}{next_inv[0]}"

    extra = []

    # full cancellations: a known line reversed a few days later
    full = known.sample(400, random_state=1)
    for r in full.itertuples(index=False):
        extra.append(dict(r._asdict(), invoice=new_invoice("C"), quantity=-r.quantity,
                          invoice_date=r.invoice_date + pd.Timedelta(days=int(rng.integers(0, 20)), minutes=7)))
    truth["full_cancellations"] = len(full)
    truth["full_cancel_value"] = float((full["quantity"] * full["price"]).sum())

    # partial returns: fewer units than were bought, so nothing to pair with
    # (only lines where no other purchase by that customer has the returned
    # quantity, so the planted answer is unambiguous)
    key = known["customer_id"] + "|" + known["stock_code"] + "|" + known["price"].astype(str)
    taken = set(key + "|" + known["quantity"].astype(str))
    half = (known["quantity"] // 2).clip(lower=1)
    clear = ~(key + "|" + half.astype(str)).isin(taken)
    part = known[(known["quantity"] >= 2) & clear].drop(full.index, errors="ignore").sample(150, random_state=2)
    for r in part.itertuples(index=False):
        extra.append(dict(r._asdict(), invoice=new_invoice("C"), quantity=-max(1, r.quantity // 2),
                          invoice_date=r.invoice_date + pd.Timedelta(days=int(rng.integers(1, 30)))))
    truth["partial_returns"] = len(part)
    truth["partial_returns_value"] = float(sum(max(1, q // 2) * p for q, p in zip(part["quantity"], part["price"])))

    # postage on some known orders
    post_inv = known.drop_duplicates("invoice").sample(300, random_state=3)
    for r in post_inv.itertuples(index=False):
        extra.append(dict(r._asdict(), stock_code="POST", description="POSTAGE", quantity=1, price=18.0))
    truth["postage_lines"] = len(post_inv)

    # free lines (price 0) with a customer
    free = known.sample(120, random_state=4)
    for r in free.itertuples(index=False):
        extra.append(dict(r._asdict(), stock_code=r.stock_code, price=0.0))
    truth["zero_price_lines"] = len(free)

    # stock corrections: negative quantity, no customer, on a normal invoice
    for _ in range(90):
        r = catalog.sample(1, random_state=int(rng.integers(1 << 31))).iloc[0]
        extra.append(dict(invoice=new_invoice(), stock_code=r.stock_code, description="damaged",
                          quantity=-int(rng.integers(1, 50)), price=r.price, customer_id=None,
                          country="United Kingdom",
                          invoice_date=_time_on(START + pd.Timedelta(days=int(rng.integers(0, 700))), rng)))
    truth["stock_adjustments"] = 90

    # bad debt write offs
    for i in range(3):
        extra.append(dict(invoice=f"A{563185 + i}", stock_code="B", description="Adjust bad debt", quantity=1,
                          price=float(rng.integers(1000, 10000)), customer_id=None, country="United Kingdom",
                          invoice_date=pd.Timestamp("2011-08-12 14:50")))
    truth["bad_debt"] = 3

    raw = pd.concat([clean_lines, pd.DataFrame(extra)], ignore_index=True)

    # exact duplicates of known sale lines
    dups = raw[raw["customer_id"].notna() & ~raw["invoice"].str.startswith("C") & (raw["price"] > 0)
               & (raw["stock_code"] != "POST")].sample(350, random_state=5)
    raw = pd.concat([raw, dups], ignore_index=True)
    truth["duplicates"] = len(dups)

    raw = raw.sort_values(["invoice_date", "invoice"], kind="stable").reset_index(drop=True)
    raw["quantity"] = raw["quantity"].astype("int64")
    for col in ("invoice", "stock_code", "description", "customer_id", "country"):
        raw[col] = raw[col].astype("string")

    # split into two sheets that overlap for a few days, as the real file does
    s1 = raw[raw["invoice_date"] < SHEET1_END].assign(sheet="Year 2009-2010")
    s2 = raw[raw["invoice_date"] >= SHEET2_START].assign(sheet="Year 2010-2011")
    truth["overlap_rows"] = int(((raw["invoice_date"] >= SHEET2_START) & (raw["invoice_date"] < SHEET1_END)).sum())
    out = []
    for s in (s1, s2):
        s = s.reset_index(drop=True)
        s.insert(0, "row_in_sheet", np.arange(len(s), dtype="int64"))
        out.append(s)
    result = pd.concat(out, ignore_index=True)
    cols = ["sheet", "row_in_sheet", "invoice", "stock_code", "description", "quantity",
            "invoice_date", "price", "customer_id", "country"]
    truth["clean_value"] = float((clean_lines.loc[clean_lines["customer_id"].notna(), "quantity"]
                                  * clean_lines.loc[clean_lines["customer_id"].notna(), "price"]).sum())
    truth["clean_known_lines"] = int(clean_lines["customer_id"].notna().sum())
    return result[cols], truth
